//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 绘图二.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("绘图二.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap AGV10off {
            get {
                object obj = ResourceManager.GetObject("AGV10off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AGV10on {
            get {
                object obj = ResourceManager.GetObject("AGV10on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AGV10sby {
            get {
                object obj = ResourceManager.GetObject("AGV10sby", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AGV11off {
            get {
                object obj = ResourceManager.GetObject("AGV11off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AGV11on {
            get {
                object obj = ResourceManager.GetObject("AGV11on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AGV11sby {
            get {
                object obj = ResourceManager.GetObject("AGV11sby", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AGV12off {
            get {
                object obj = ResourceManager.GetObject("AGV12off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AGV12on {
            get {
                object obj = ResourceManager.GetObject("AGV12on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AGV12sby {
            get {
                object obj = ResourceManager.GetObject("AGV12sby", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AGV13off {
            get {
                object obj = ResourceManager.GetObject("AGV13off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AGV13on {
            get {
                object obj = ResourceManager.GetObject("AGV13on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AGV13sby {
            get {
                object obj = ResourceManager.GetObject("AGV13sby", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AGV1off {
            get {
                object obj = ResourceManager.GetObject("AGV1off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AGV1on {
            get {
                object obj = ResourceManager.GetObject("AGV1on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AGV1sby {
            get {
                object obj = ResourceManager.GetObject("AGV1sby", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AGV2off {
            get {
                object obj = ResourceManager.GetObject("AGV2off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AGV2on {
            get {
                object obj = ResourceManager.GetObject("AGV2on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AGV2sby {
            get {
                object obj = ResourceManager.GetObject("AGV2sby", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AGV3off {
            get {
                object obj = ResourceManager.GetObject("AGV3off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AGV3on {
            get {
                object obj = ResourceManager.GetObject("AGV3on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AGV3sby {
            get {
                object obj = ResourceManager.GetObject("AGV3sby", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AGV4off {
            get {
                object obj = ResourceManager.GetObject("AGV4off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AGV4on {
            get {
                object obj = ResourceManager.GetObject("AGV4on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AGV4sby {
            get {
                object obj = ResourceManager.GetObject("AGV4sby", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AGV5off {
            get {
                object obj = ResourceManager.GetObject("AGV5off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AGV5on {
            get {
                object obj = ResourceManager.GetObject("AGV5on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AGV5sby {
            get {
                object obj = ResourceManager.GetObject("AGV5sby", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AGV6off {
            get {
                object obj = ResourceManager.GetObject("AGV6off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AGV6on {
            get {
                object obj = ResourceManager.GetObject("AGV6on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AGV6sby {
            get {
                object obj = ResourceManager.GetObject("AGV6sby", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AGV7off {
            get {
                object obj = ResourceManager.GetObject("AGV7off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AGV7on {
            get {
                object obj = ResourceManager.GetObject("AGV7on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AGV7sby {
            get {
                object obj = ResourceManager.GetObject("AGV7sby", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AGV8off {
            get {
                object obj = ResourceManager.GetObject("AGV8off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AGV8on {
            get {
                object obj = ResourceManager.GetObject("AGV8on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AGV8sby {
            get {
                object obj = ResourceManager.GetObject("AGV8sby", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AGV9off {
            get {
                object obj = ResourceManager.GetObject("AGV9off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AGV9on {
            get {
                object obj = ResourceManager.GetObject("AGV9on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AGV9sby {
            get {
                object obj = ResourceManager.GetObject("AGV9sby", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Backgroud01 {
            get {
                object obj = ResourceManager.GetObject("Backgroud01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap backgroud02 {
            get {
                object obj = ResourceManager.GetObject("backgroud02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BcurrentPT {
            get {
                object obj = ResourceManager.GetObject("BcurrentPT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bstate {
            get {
                object obj = ResourceManager.GetObject("Bstate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Btarget {
            get {
                object obj = ResourceManager.GetObject("Btarget", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bvelocity {
            get {
                object obj = ResourceManager.GetObject("Bvelocity", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Num0 {
            get {
                object obj = ResourceManager.GetObject("Num0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Num10g {
            get {
                object obj = ResourceManager.GetObject("Num10g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Num10r {
            get {
                object obj = ResourceManager.GetObject("Num10r", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Num11g {
            get {
                object obj = ResourceManager.GetObject("Num11g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Num11r {
            get {
                object obj = ResourceManager.GetObject("Num11r", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Num12g {
            get {
                object obj = ResourceManager.GetObject("Num12g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Num12r {
            get {
                object obj = ResourceManager.GetObject("Num12r", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Num13g {
            get {
                object obj = ResourceManager.GetObject("Num13g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Num13r {
            get {
                object obj = ResourceManager.GetObject("Num13r", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Num1g {
            get {
                object obj = ResourceManager.GetObject("Num1g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Num1r {
            get {
                object obj = ResourceManager.GetObject("Num1r", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Num2g {
            get {
                object obj = ResourceManager.GetObject("Num2g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Num2r {
            get {
                object obj = ResourceManager.GetObject("Num2r", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Num3g {
            get {
                object obj = ResourceManager.GetObject("Num3g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Num3r {
            get {
                object obj = ResourceManager.GetObject("Num3r", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Num4g {
            get {
                object obj = ResourceManager.GetObject("Num4g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Num4r {
            get {
                object obj = ResourceManager.GetObject("Num4r", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Num5g {
            get {
                object obj = ResourceManager.GetObject("Num5g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Num5r {
            get {
                object obj = ResourceManager.GetObject("Num5r", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Num6g {
            get {
                object obj = ResourceManager.GetObject("Num6g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Num6r {
            get {
                object obj = ResourceManager.GetObject("Num6r", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Num7g {
            get {
                object obj = ResourceManager.GetObject("Num7g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Num7r {
            get {
                object obj = ResourceManager.GetObject("Num7r", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Num8g {
            get {
                object obj = ResourceManager.GetObject("Num8g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Num8r {
            get {
                object obj = ResourceManager.GetObject("Num8r", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Num9g {
            get {
                object obj = ResourceManager.GetObject("Num9g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Num9r {
            get {
                object obj = ResourceManager.GetObject("Num9r", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap run {
            get {
                object obj = ResourceManager.GetObject("run", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Signal {
            get {
                object obj = ResourceManager.GetObject("Signal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap speed {
            get {
                object obj = ResourceManager.GetObject("speed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap stop {
            get {
                object obj = ResourceManager.GetObject("stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Target10d {
            get {
                object obj = ResourceManager.GetObject("Target10d", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Target10u {
            get {
                object obj = ResourceManager.GetObject("Target10u", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Target11d {
            get {
                object obj = ResourceManager.GetObject("Target11d", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Target11u {
            get {
                object obj = ResourceManager.GetObject("Target11u", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Target12d {
            get {
                object obj = ResourceManager.GetObject("Target12d", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Target12u {
            get {
                object obj = ResourceManager.GetObject("Target12u", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Target1d {
            get {
                object obj = ResourceManager.GetObject("Target1d", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Target1u {
            get {
                object obj = ResourceManager.GetObject("Target1u", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Target2d {
            get {
                object obj = ResourceManager.GetObject("Target2d", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Target2u {
            get {
                object obj = ResourceManager.GetObject("Target2u", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Target3d {
            get {
                object obj = ResourceManager.GetObject("Target3d", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Target3u {
            get {
                object obj = ResourceManager.GetObject("Target3u", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Target4d {
            get {
                object obj = ResourceManager.GetObject("Target4d", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Target4u {
            get {
                object obj = ResourceManager.GetObject("Target4u", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Target5d {
            get {
                object obj = ResourceManager.GetObject("Target5d", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Target5u {
            get {
                object obj = ResourceManager.GetObject("Target5u", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Target6d {
            get {
                object obj = ResourceManager.GetObject("Target6d", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Target6u {
            get {
                object obj = ResourceManager.GetObject("Target6u", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Target7d {
            get {
                object obj = ResourceManager.GetObject("Target7d", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Target7u {
            get {
                object obj = ResourceManager.GetObject("Target7u", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Target8d {
            get {
                object obj = ResourceManager.GetObject("Target8d", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Target8u {
            get {
                object obj = ResourceManager.GetObject("Target8u", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Target9d {
            get {
                object obj = ResourceManager.GetObject("Target9d", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Target9u {
            get {
                object obj = ResourceManager.GetObject("Target9u", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap welcome {
            get {
                object obj = ResourceManager.GetObject("welcome", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
